version: "3.9"

services:
  db:
    image: mysql
    cap_add:
      - SYS_NICE
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSSQL_DATABASE: my_db
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_db:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']
  server:
    build: .
    command: npm start
    volumes:
      - .:/server
      - /server/node_modules
    ports:
      - "3333:3000"
    depends_on:
      - db
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "8888:8080"
    depends_on:
      - server
volumes:
  mysql_db: {}
